/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package demojavafxapplication;

import ModelClasses.DropDownModel;
import ModelClasses.NodeModel;
import ModelClasses.PropertiesModel;
import ModelClasses.TextAreaModel;
import ModelClasses.TextBoxModel;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.codehaus.jackson.map.ObjectMapper;

/**
 *
 * @author Welcome
 */
public class CreateNode extends javax.swing.JFrame {

    /**
     * Creates new form ModelManager
     */
    public CreateNode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nodeNameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Create Node");

        jLabel1.setText("Node Name:");

        nodeNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nodeNameFieldActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton)
                    .addComponent(nodeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nodeNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(saveButton)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nodeNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nodeNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nodeNameFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        String nodeName =  nodeNameField.getText();
        nodeNameField.setText("");
        ObjectMapper mapper = new ObjectMapper();
        NodeModel node = new NodeModel();
        node.setName(nodeName);
//        TextBoxModel t1 = new TextBoxModel();
//        t1.setIsRequired("yes");
//        t1.setLabel("title");
//        t1.setType("textbox");
//        
//        TextBoxModel t2 = new TextBoxModel();
//        t2.setIsRequired("yes");
//        t2.setLabel("id");
//        t2.setType("textbox");
//        
//        DropDownModel d1=new DropDownModel();
//        d1.setLabel("status");
//        d1.setType("dropdown");
//        d1.setIsRequired("yes");
//        List<String> valuesd1=new <String>ArrayList();
//        valuesd1.add("Open");
//        valuesd1.add("In-Progress");
//        valuesd1.add("Complete");
//        d1.setValues(valuesd1);
//        d1.setDefaultValue("Open");
//        
//        DropDownModel d2=new DropDownModel();
//        d2.setLabel("priority");
//        d2.setType("dropdown");
//        d2.setIsRequired("yes");
//        List<String> valuesd2=new <String>ArrayList();
//        valuesd2.add("high");
//        valuesd2.add("medium");
//        valuesd2.add("low");
//        d2.setValues(valuesd2);
//        d2.setDefaultValue("low");
//        
//        TextAreaModel ta1 = new TextAreaModel();
//        ta1.setLabel("Steps to reproduce");
//        ta1.setType("textarea");
//        ta1.setIsRequired("no");
//        
//        TextAreaModel ta2 = new TextAreaModel();
//        ta2.setLabel("Expected Results");
//        ta2.setType("textarea");
//        ta2.setIsRequired("no");
        
        PropertiesModel p1 = new PropertiesModel();
        List<TextBoxModel> textBoxList = new <TextBoxModel> ArrayList();
        List<TextAreaModel> textAreaList = new <TextAreaModel> ArrayList();
        List<DropDownModel> dropDownList = new <DropDownModel> ArrayList();
        //textBoxList.add(t1);
        //textBoxList.add(t2);
        //textAreaList.add(ta1);
        //textAreaList.add(ta2);
        //dropDownList.add(d1);
        //dropDownList.add(d2);
        p1.setTextBoxProperties(textBoxList);
        p1.setTextAreaProperties(textAreaList);
        p1.setDropDownProperties(dropDownList);
        node.setProperties(p1);
        String workingDir = System.getProperty("user.dir");
        try {
            //Object to JSON in file
            File f = new File(workingDir+"\\temp\\"+nodeName +".json");
            f.getParentFile().mkdirs();
            if(f.exists()){
                System.out.println("file already present");
                //f.delete();
                //mapper.defaultPrettyPrintingWriter().writeValue(new File(workingDir+"\\temp\\"+nodeName +".json"), node);
            JOptionPane.showMessageDialog(null, "Node:"+" " + nodeName +" already present");    
            }
            else{
                System.out.println("new file");
                mapper.defaultPrettyPrintingWriter().writeValue(new File(workingDir+"\\temp\\"+nodeName +".json"), node);
                    }
            //mapper.writeValue(new File(workingDir+"\\"+nodeName +".json"), node);
            
//Object to JSON in String
//String jsonInString = mapper.writeValueAsString(obj);
        } catch (IOException ex) {
            Logger.getLogger(CreateNode.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Node:"+" " + nodeName +" added successfully");
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateNode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateNode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateNode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateNode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateNode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nodeNameField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
